{
 "title": "Fin",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "avg(rate(stanje_obraz[1m]))", "legendFormat": "{{Value obraz}}" },
    { "expr": "avg(rate(stanje_oci[1m]))", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Memory Used (Kafka)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"kafka\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Speed of Neural Network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nn_eye_detections_total[1m])) + sum(rate(nn_head_detections_total[1m]))",
     "legendFormat": "Frames"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "options": {
    "content": "# SPO System\n\nDiagnostics for SPO System"
   }
  },
  {
   "title": "Trenutno zaznano stanje obraza",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stanje_obraz{stanje_obraz=\"utrujen\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trenutno zaznano stanje oči",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stanje_oci{stanje_oci=\"zaprte\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages In Per Topic (frame_noticifation)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"frame_noticifation\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "CPU Usage (Kafka)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(process_cpu_seconds_total{job=\"kafka\"}[1m])) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic (frame_rezulatati)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"frame_rezultati\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "CPU Usage (Algorithm)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(process_cpu_seconds_total{job=\"process-exporter\"}[1m])) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage Exporter(Algorithm)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cpu_process{job=\"python-neuralnetwork\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic (frame_noticifation)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesin_total{topic=\"frame_noticifation\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic (frame_rezultati)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesin_total{topic=\"frame_rezultati\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}