FROM wurstmeister/kafka
ADD jmx_prometheus_config.yml /usr/app/jmx_prometheus_config.yml
ADD https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.18.0/jmx_prometheus_javaagent-0.18.0.jar /usr/app/jmx_prometheus.jar